name: CI
on: [push, pull_request]

jobs:

  test_memory:
    name: Node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16', '18', '20']
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - run: npm run test_memory
        env:
          CI: true

  test_redis:
    name: Node ${{ matrix.node }}, Redis ${{ matrix.redis-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16', '18', '20']
        redis-version: [5, 6, 7]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Start Redis v${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: npm install

      - run: npm run test_redis
        env:
          CI: true

  test_mongo:
    name: Node ${{ matrix.node }}, MongoDB ${{ matrix.mongodb-version }}. Multi collection (default)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16', '18', '20']
        mongodb-version: [6, 7]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install

      - run: npm install mongodb@6
      - run: npm run test_mongo
      - run: npm install mongodb@5
      - run: npm run test_mongo

  test_mongo_single:
    name: Node ${{ matrix.node }}, MongoDB ${{ matrix.mongodb-version }}. Single collection
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16', '18', '20']
        mongodb-version: [6, 7]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install

      - run: npm install mongodb@6
      - run: npm run test_mongo_single
      - run: npm install mongodb@5
      - run: npm run test_mongo_single
